# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'katalog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_katalog(object):
    def setupUi(self, katalog):
        katalog.setObjectName("katalog")
        katalog.setWindowModality(QtCore.Qt.WindowModal)
        katalog.resize(960, 540)
        self.label = QtWidgets.QLabel(katalog)
        self.label.setGeometry(QtCore.QRect(0, 0, 961, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(katalog)
        self.textBrowser.setGeometry(QtCore.QRect(40, 50, 181, 111))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(katalog)
        QtCore.QMetaObject.connectSlotsByName(katalog)

    def retranslateUi(self, katalog):
        _translate = QtCore.QCoreApplication.translate
        katalog.setWindowTitle(_translate("katalog", "chernokolpakov"))
        self.label.setText(_translate("katalog", "Лучшие Предложения!"))
