# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'katalog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_katalog(object):
    def setupUi(self, katalog):
        katalog.setObjectName("katalog")
        katalog.setWindowModality(QtCore.Qt.WindowModal)
        katalog.resize(960, 540)
        self.Image = QtWidgets.QLabel(katalog)
        self.Image.setGeometry(QtCore.QRect(10, 60, 461, 271))
        self.Image.setAutoFillBackground(False)
        self.Image.setStyleSheet("\n"
"\n"
"border: 3px solid black;\n"
"backgroun-image:cover;")
        self.Image.setText("")
        self.Image.setObjectName("Image")
        self.NextButton = QtWidgets.QPushButton(katalog)
        self.NextButton.setGeometry(QtCore.QRect(20, 410, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.NextButton.setFont(font)
        self.NextButton.setObjectName("NextButton")
        self.PrevButton = QtWidgets.QPushButton(katalog)
        self.PrevButton.setGeometry(QtCore.QRect(250, 410, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PrevButton.setFont(font)
        self.PrevButton.setObjectName("PrevButton")
        self.label_2 = QtWidgets.QLabel(katalog)
        self.label_2.setGeometry(QtCore.QRect(500, 230, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(katalog)
        self.textBrowser.setGeometry(QtCore.QRect(500, 60, 421, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(katalog)
        QtCore.QMetaObject.connectSlotsByName(katalog)

    def retranslateUi(self, katalog):
        _translate = QtCore.QCoreApplication.translate
        katalog.setWindowTitle(_translate("katalog", "chernokolpakov"))
        self.NextButton.setText(_translate("katalog", "Назад"))
        self.PrevButton.setText(_translate("katalog", "Вперед"))
