# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'katalog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_katalog(object):
    def setupUi(self, katalog):
        katalog.setObjectName("katalog")
        katalog.setWindowModality(QtCore.Qt.WindowModal)
        katalog.resize(960, 540)
        self.label = QtWidgets.QLabel(katalog)
        self.label.setGeometry(QtCore.QRect(0, 0, 961, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Image = QtWidgets.QLabel(katalog)
        self.Image.setGeometry(QtCore.QRect(230, 60, 461, 271))
        self.Image.setText("")
        self.Image.setObjectName("Image")
        self.NextButton = QtWidgets.QPushButton(katalog)
        self.NextButton.setGeometry(QtCore.QRect(230, 390, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.NextButton.setFont(font)
        self.NextButton.setObjectName("NextButton")
        self.PrevButton = QtWidgets.QPushButton(katalog)
        self.PrevButton.setGeometry(QtCore.QRect(550, 390, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PrevButton.setFont(font)
        self.PrevButton.setObjectName("PrevButton")

        self.retranslateUi(katalog)
        QtCore.QMetaObject.connectSlotsByName(katalog)

    def retranslateUi(self, katalog):
        _translate = QtCore.QCoreApplication.translate
        katalog.setWindowTitle(_translate("katalog", "chernokolpakov"))
        self.label.setText(_translate("katalog", "Лучшие Предложения!"))
        self.NextButton.setText(_translate("katalog", "Назад"))
        self.PrevButton.setText(_translate("katalog", "Вперед"))
