# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prodaga.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Prodaga(object):
    def setupUi(self, Prodaga):
        Prodaga.setObjectName("Prodaga")
        Prodaga.resize(400, 300)
        self.Sizelabel = QtWidgets.QLabel(Prodaga)
        self.Sizelabel.setGeometry(QtCore.QRect(130, 120, 171, 16))
        self.Sizelabel.setText("")
        self.Sizelabel.setObjectName("Sizelabel")
        self.pushButton = QtWidgets.QPushButton(Prodaga)
        self.pushButton.setGeometry(QtCore.QRect(150, 260, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Prodaga)
        self.label.setGeometry(QtCore.QRect(60, 120, 61, 16))
        self.label.setObjectName("label")
        self.NameBrowser = QtWidgets.QTextBrowser(Prodaga)
        self.NameBrowser.setGeometry(QtCore.QRect(10, 20, 381, 61))
        self.NameBrowser.setObjectName("NameBrowser")
        self.label_2 = QtWidgets.QLabel(Prodaga)
        self.label_2.setGeometry(QtCore.QRect(60, 170, 61, 16))
        self.label_2.setObjectName("label_2")
        self.spinBox = QtWidgets.QSpinBox(Prodaga)
        self.spinBox.setGeometry(QtCore.QRect(160, 210, 61, 21))
        self.spinBox.setObjectName("spinBox")
        self.label_4 = QtWidgets.QLabel(Prodaga)
        self.label_4.setGeometry(QtCore.QRect(130, 170, 171, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Prodaga)
        QtCore.QMetaObject.connectSlotsByName(Prodaga)

    def retranslateUi(self, Prodaga):
        _translate = QtCore.QCoreApplication.translate
        Prodaga.setWindowTitle(_translate("Prodaga", "Form"))
        self.pushButton.setText(_translate("Prodaga", "OK"))
        self.label.setText(_translate("Prodaga", "Размер"))
        self.label_2.setText(_translate("Prodaga", "Цена"))
