# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vozvrat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 480)
        self.MaintableWidget = QtWidgets.QTableWidget(Form)
        self.MaintableWidget.setGeometry(QtCore.QRect(30, 10, 660, 350))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.MaintableWidget.setFont(font)
        self.MaintableWidget.setObjectName("MaintableWidget")
        self.MaintableWidget.setColumnCount(0)
        self.MaintableWidget.setRowCount(0)
        self.VozvratButton = QtWidgets.QPushButton(Form)
        self.VozvratButton.setGeometry(QtCore.QRect(190, 420, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.VozvratButton.setFont(font)
        self.VozvratButton.setAutoExclusive(False)
        self.VozvratButton.setObjectName("VozvratButton")
        self.BrakButton = QtWidgets.QPushButton(Form)
        self.BrakButton.setGeometry(QtCore.QRect(380, 420, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.BrakButton.setFont(font)
        self.BrakButton.setAutoExclusive(False)
        self.BrakButton.setObjectName("BrakButton")
        self.otdateEdit = QtWidgets.QDateEdit(Form)
        self.otdateEdit.setGeometry(QtCore.QRect(210, 370, 110, 22))
        self.otdateEdit.setDate(QtCore.QDate(2021, 12, 27))
        self.otdateEdit.setObjectName("otdateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(Form)
        self.dateEdit_2.setGeometry(QtCore.QRect(380, 370, 110, 22))
        self.dateEdit_2.setDate(QtCore.QDate(2021, 12, 27))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.SortButton = QtWidgets.QPushButton(Form)
        self.SortButton.setGeometry(QtCore.QRect(530, 370, 93, 28))
        self.SortButton.setObjectName("SortButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.VozvratButton.setText(_translate("Form", "Возврат"))
        self.BrakButton.setText(_translate("Form", "Брак"))
        self.SortButton.setText(_translate("Form", "Применить"))
